### ISSUE TITLE
s/Addresses/ScriptHashes

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/common-blockchain#17]
This idea came back to my attention in #16, where bloom filters could either use script hashes solely, or it could use addresses.
Remembering the latter is a subset of the former in that addresses are simply encoded scripts.

Using script hashes instead of addresses means less work for the server, and greater flexibility for the client for all kinds of transactions.

Example pseudo-code on how this could work with existing APIs:

``` javascript
var bitcoin = require('bitcoinjs-lib')
var addresses = ["mpRZxxp5FtmQipEWJPa1NY9FmPsva3exUd", ..]
var scripts = addresses.map((x) => { return bitcoin.Address.toOutputScript(x) }
// if the raw scripts are too 'big', we could use the script hashes instead, solely

blockchain.scripts.transactions(scripts, function(err, results) {
    // ...
})

blockchain.scripts.summary(scripts, function(err, results) {
    // ...
})

blockchain.scripts.unspents(scripts, function(err, results) {
    // ...
})
```

If we wanted to keep the `Addresses.*` API, we could just add convenience functions to do the above (`addresses.map( ...`).

IMHO, this will allow the community to grow and do more cool stuff that can't be done with address based API's right now.

**Comment by dcousens** [comment]
This is definitely not something that will be cross-compatible across nodes, so it will have to follow that we push this kind of API to the nodes through requests and committing to [insight-api](https://github.com/bitpay/insight-api) and what not.

**Comment by dcousens** [comment]
@rubensayshi @weilu @jprichardson thoughts?

**Comment by dcousens** [comment]
This API would mean we could query things like the unspents of a particular `OP_RETURN`.

**Comment by rubensayshi** [comment]
hmm, for me personally I can't implement this easily because we can't easily set indexes on the scripts ...

**Comment by dcousens** [comment]
You already do it?  You have to do it to get the addresses in the first
place.

**Comment by dcousens** [comment]
Oh, you mean using existing indexes?  Then yes.   It would mean replacing
your address index entirely.

**Comment by dcousens** [comment]
But,  as scary as that sounds, remember this is only because,  as a
community, we've artificially limited ourselves to this subset of
functionality simply because it is human readable.

**Comment by jprichardson** [comment]
Yes, I really like this. But aren't we limited to what API providers provide? Is the goal of adding this API in the hopes that API providers will follow? I'm wondering if they wouldn't just to err on the side of practicality. But overall, your idea makes a lot of sense.

**Comment by dcousens** [comment]
I think if we can help set a standard for what is expected, and help make
it happen via PRs to the right repositories,  then others will follow soon
after.

**Comment by rubensayshi** [comment]
I think it fits common-blockchain because we basicly already made a bunch of asumptions about the context;

 - the user is using a library like bitcoinjs-lib or similar which is capable of doing most things related to parsing and generating raw data (tx, script, block)
 - parsing raw data is prefered over providing parsed json (because it's less data across the wire and if you want to validate data you'd have to construct something out of the parsed data anyway)
 -  the user knows enough about bitcoin to not have a problem parsing raw data and extracting what they need

**when I say user I mean developer ;-)*

addresses are indeed just something to make things a little more user friendly and easier, both for end users and developers.  

for our current API (blocktrail) we're trying to make things as easy as possible for developers relatively new(bish) to bitcoin, thus parsing the txs and providing extra (extracted) data and letting them use addresses make sence.

but the asumptions made so far for the context of common-blockchain already go in the direction that convenience / low entry is not a goal  
and using scripts is not that much hassle (as you provided a 2 line snippet to do it) and it's more future proof than addresses

**Comment by weilu** [comment]
@dcousens does helloblock already support querying with ScriptPubKeys? I like the ScriptPubKey idea moving forwards. At the same time I think we should not make it part of the API until at least one provider supports it. I understand your whole "set an example" point. I just thought that it's not realistic to expect devs to use them until they can get actual benefit out of it.

**Comment by dcousens** [comment]
No,  and Helloblock is going to be disbanding soon enough, so its not a
viable alternative going forward anyway.

**Comment by dcousens** [comment]
This works great on my own prototypes.  I currently use SHA1 (160 bit) hashes for indexing the scripts,  with no special behaviour, just `sha1(scriptSig OR scriptPubKey)`.

Incredibly effective queries, the lookups are actually smaller too.
