### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by rubensayshi** [common-blockchain/common-blockchain#19]
Having some examples or a small example app would make it easier for people to understand how cb is best used.

and it would make it easier to discuss and think about more advanced features such as SPV

**Comment by jprichardson** [comment]
:+1:

**Comment by dcousens** [comment]
Agreed,  any idea on where we should put them?

**Comment by rubensayshi** [comment]
idk, maybe a small (wallet) project that can work as example (can also function as example project for bitcoinjs-lib at the same time ;-))

**Comment by carnesen** [comment]
+1. I'm having a hard time figuring out how I might use common-blockchain.

**Comment by jprichardson** [comment]
@carnesen could you elaborate a little more? `common-blockchain` is just a spec. There are many adapters that implement all or partially implement the spec. Each adapter should have some documentation associated with it explaining its usage.

So if you wanted to use `Bitpay Insight`, you'd use: https://github.com/jprichardson/cb-insight (note: needs a lot of work). If you wanted to use `Blockr`, you'd use https://github.com/weilu/cb-blockr. The idea is that you can just swap modules if you want to switch services. In practice, this isn't usually the case, but it does help to have a standardized interface. I believe that @rubensayshi's company BlockTrail even has a Common Blockchain compatible API endpoint.

Hopefully that helps some. We have a long way to go before we hit our goals, but we're slowly working our way there.

**Comment by carnesen** [comment]
Thanks for the reply. I'm happy to elaborate on my question. From your reply, it sounds like common-blockchain spec is mostly for informational purposes only. A spec is always at least that, but need not be only that. I'm thinking of projects like [Swagger](http://swagger.io/) where the spec can be used to generate both client and server code in a bunch of different languages, beautiful interactive documentation, all sorts of stuff. What's the schema for the common-blockchain spec? It's not 100% clear to me from reading the readme and types.json what the actual endpoints are supposed to be. For example, I'd guess the http verb is always "GET". Is that right? (But what about PUT endpoints for broadcasting transactions, for example?). Another example, I'd guess that [Addresses.Summary](https://github.com/common-blockchain/common-blockchain#addressessummary) means that a cb-compliant API serves an /addresses/summary endpoint, or is it /Addresses/Summary or case-insensitive? And what does the "?" in "?String" mean? I'm guessing it means that value might not always be present, but how should the absence of a value be represented in the response (e.g. empty string, null,  field is absent)? For "arguments", which I think would be better described as "parameters", there are a number of different ways data can be sent in an http request. Which one does a cb-compliant API use? I'm guessing it's always query-string parameters. I'll also mention in passing that the spec should distinguish between Number types at least to have an Integer type. The distinction is particularly important in JavaScript, which doesn't have native support for integers.

By way of background, I dreamed up my own spec schema to describe the Bitcoin Core RPC API: 

https://github.com/carnesen/bitcoin-rpc/tree/master/lib/yml

I then wrote a client that reads those spec files. I'm currently considering how I can make that spec more widely useful, for example by writing a program that translates it into the Swagger schema. 

I'll now propose an answer to my questions: rewrite the common-blockchain to conform to the Swagger schema! Preferably in yaml instead of json.

**Comment by jprichardson** [comment]
Common blockchain is a spec for API consumers, not implementers. it includes a test module to check if the consumer API conforms. Details like PUT/POST are determined by API producers. The entire purpose of Common blockchain AFAIK is so that developers can switch Blockchain providers easily. May not work perfectly in practice, but in my experience it works pretty well.

As far as JSON/YAML... why the bikeshed? Does it really matter? Semi-related: discussion on GraphQL: https://github.com/common-blockchain/common-blockchain/issues/23

**Comment by carnesen** [comment]
Maybe I get it now. That first sentence of the readme threw me off: "A
standard REST API specification for comprehensive bitcoin block explorers."
It's a spec for methods of objects, not for REST API calls. Is that right?
I mean if it doesn't specify the http verbs and urls, it can't very well be
called a REST API spec.

I'm a YAML evangelist. It's as machine-readable as JSON and twice as
human-readable. So easy to switch programmatically, literally a few lines,
and so worth it for something like a spec whose goal in life is to be read
by humans.

**Comment by jprichardson** [comment]
> That first sentence of the readme threw me off: "A
standard REST API specification for comprehensive bitcoin block explorers."
It's a spec for methods of objects, not for REST API calls. Is that right?
I mean if it doesn't specify the http verbs and urls, it can't very well be
called a REST API spec.

Totally agree. That was a bad description. Sorry about that.

**Comment by dcousens** [comment]
@jprichardson ideas for what we should write there instead?

**Comment by jprichardson** [comment]
@dcousens what about removing the mention of REST? I mean, correct me if I'm wrong, but Common Blockchain is about API consumers right? Wouldn't this implicitly mean that it has nothing to do with REST? Maybe I was missing part of the vision?

**Comment by dcousens** [comment]
Removed mention of REST in https://github.com/common-blockchain/common-blockchain/commit/80e138728456878b6419fa8276a774ab7ef516b8
